apiVersion: apps/v1
kind: Deployment
metadata:
  name: { { include "my-web-app.fullname" . } }
  labels: { { - include "my-web-app.labels" . | nindent 4 } }
spec:
  replicas: { { .Values.replicaCount } }
  selector:
    matchLabels: { { - include "my-web-app.selectorLabels" . | nindent 6 } }
  template:
    metadata:
      labels: { { - include "my-web-app.selectorLabels" . | nindent 8 } }
    spec:
      containers:
        - name: { { .Chart.Name } }
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: { { .Values.image.pullPolicy } }
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
